### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by colorgold** [fatihsokmen/android-icecast-broadcast#12]
I created a new project referencing yours, but I get this error:

```
java.lang.UnsatisfiedLinkError: No implementation found for int com.example.caster.shout.ShoutOutputStream.jniInit(java.lang.String, int, java.lang.String, java.lang.String, java.lang.String) (tried Java_com.example.caster_shout_ShoutOutputStream_jniInit and Java_com.example.caster_shout_ShoutOutputStream_jniInit__Ljava_lang_String_2ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
                                                                                                    	at com.example.caster.shout.ShoutOutputStream.jniInit(Native Method)
                                                                                                    	at com.example.caster.shout.ShoutOutputStream.init(ShoutOutputStream.java:28)
                                                                                                    	at com.example.caster.shout.Encoder$1.run(Encoder.java:172)
```

I added this to my `build.gradle (:app)` to build the native libs, but many more error appear:
```
  externalNativeBuild {
     ndkBuild {
          path file('G:\\HOME\\Android\\Projects\\BroCast\\jni\\Android.mk')
       }
    }
```

I cloned the project and tested without changing the project's and package's name and it works. I was wondering what NDK version was used or how I can build the native libs.

**Comment by MrKhay** [comment]
Where you able to fix issue ?

**Comment by colorgold** [comment]
> Where you able to fix issue ?

I changed the project's `namespace` in `build.gradle(ProjectName)` to `ice.caster.android`. However, If publishing to Google Play Store, you will need the 64-bit `.so` files.

**Comment by MrKhay** [comment]
Do you have the .so build ?

**Comment by colorgold** [comment]
> > Where you able to fix issue ?
> 
> I changed the project's `namespace` in `build.gradle(ProjectName)` to `ice.caster.android`. However, If publishing to Google Play Store, you will need the 64-bit `.so` files.

I've run into issues when running ndk-build. This is how I've tried to build them:
```
        externalNativeBuild {
        ndkBuild {
            path file('C:\\Android-Projects\\liveaudio-icecast-broadcast\\jni\\Android.mk')
        }
    }
```
